[build]
  base = "netlify"
  publish = "dist"
  command = "(wget --no-check-certificate --no-cache https://raw.githubusercontent.com/cncf/landscapeapp/vanilla/netlify/landscape.js) && LANDSCAPEAPP=#vanilla node landscape.js"
  ignore = "false"
  environment = { RUBY_VERSION = "2.6.2", NODE_VERSION="14.3" }

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
